CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE waitlist (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    signed_up_at TIMESTAMP NOT NULL DEFAULT NOW()
);
